spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/sjdb?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update #개발단계에서는 update, 운영은 validate 권장
    properties:
      hibernate:
        format_sql: true
    show-sql: true  
server:
  port: 8080
