spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leetsdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: "0902"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port:8080